import os
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles

# ==========================================
# 🌐 IMPORT ROUTERS
# ==========================================
from avatar_chat import router as avatar_chat_router
from live_translation import router as live_translation_router

# ==========================================
# 🚀 APP INITIALIZATION
# ==========================================
app = FastAPI(title="AI Avatar Backend")

# 🛡️ CORS Configuration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# 📁 Ensure static directory exists
os.makedirs("static", exist_ok=True)

# 📂 Mount static files
app.mount("/static", StaticFiles(directory="static"), name="static")

# ==========================================
# 🔗 INCLUDE ROUTERS
# ==========================================
app.include_router(avatar_chat_router)
app.include_router(live_translation_router)

# ==========================================
# 🌐 SHARED ENDPOINT: Translation Audio
# ==========================================
@app.get("/translation_audio/{filename}")
async def get_translation_audio(filename: str):
    """Serves audio files generated by live_translation.py"""
    return FileResponse(f"static/{filename}", media_type="audio/mpeg")